# Generated by Django 3.0.8 on 2020-10-17 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_usersvoicetry_created_dt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersvoicetry',
            options={'verbose_name': 'Reconocimiento de voz', 'verbose_name_plural': 'Reconocimientos de voces'},
        ),
        migrations.CreateModel(
            name='UsersFaceTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.FileField(blank=True, default=None, null=True, upload_to='FaceTry')),
                ('created_dt', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reconocimiento de rostro',
                'verbose_name_plural': 'Reconocimientos de rostros',
            },
        ),
    ]
